# -*- coding: utf-8 -*-
"""gradio_demo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a3BBShAQ0CJPIGKM5w1kWU3ddH1jl5Wb
"""

pip install gradio

#pip install gradio
#gradio: 一個讓你快速建立網頁讓別人適用你的功能的工具

import gradio as gr


def hello(name):
    return f"Hello {name}"


hello('Test')

gr.Interface(hello, "text","text" ).launch(share=True) #自動註冊一個應用，並在gradio官方建立一個你的應用網址

#demo1: 國語字典
import requests

def lookup(word):
  url = f"https://www.moedict.tw/uni/{word}"
  data = requests.get(url).json()
  return data['heteronyms'][0]['definitions'][0]['def']

gr.Interface(lookup,
      gr.Textbox(label="輸入國字或詞語"),
      gr.Textbox(label="查詢結果"),
      title="國語字典",
      description="請輸入欲查詢之國字").launch(share=True)

#demo2: 多輸入、多輸出

def bmi(w,h):
  ht = ""
  b = w / h**2
  if b < 18.5:
    ht = "過輕"
  elif b > 24:
    ht = "過重"
  else:
    ht = "正常"
  return b , ht
gr.Interface(bmi,
    ["number","number"],
    ["text","text"],
    examples=[
      [80,1.83],
      [85,1.83]
    ]
    ).launch(share=True)

#demo3 加入img
#pip install pillow
from PIL import Image

def process(image):
  r, g, b = image.split()
  image = Image.merge("RGB", (b,g,r))
  return image

gr.Interface(process,
      gr.Image(type="pil"),
      gr.Image(type="pil")).launch()

#im = Image.open("image.jpg")

#demo4 儲存使用者上傳之圖片 (可大量蒐集圖片)
import random

def process(images):
  image.save(f"{random.randint(0,99999):05}.jpg")
  r, g, b = image.split()
  image = Image.merge("RGB", (b,g,r))
  return image

gr.Interface(process,
      gr.Image(type="pil"),
      gr.Image(type="pil")).launch()

#demo5: 認證
import requests

def lookup(word):
  url = f"https://www.moedict.tw/uni/{word}"
  data = requests.get(url).json()
  return data['heteronyms'][0]['definitions'][0]['def']

gr.Interface(lookup,
      gr.Textbox(label="輸入國字或詞語"),
      gr.Textbox(label="查詢結果"),
      title="國語字典",
      description="請輸入欲查詢之國字",
      ).launch(share=True, auth=('test','1234'))

pip install transformers

#demo6: 整合transformers 內建model

import gradio as gr
from transformers import pipeline
pipe = pipeline("image-classification")
gr.Interface.from_pipeline(pipe).launch()

## gradio只能擺放72hr

## https://huggingface.co 可以放很久