# -*- coding: utf-8 -*-
"""20220902.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19a9gn-IDILaju4ipvFxwCh6p4bt0yE7Y

# 20220902-中華電信微課程-gradio

## Hello World 範例
"""

!pip install gradio

import gradio as gr

def hello(name):
  return f"Hello {name}"

hello('Victor')

gr.Interface(hello, "text", "text").launch()

"""## 寫一個國語字典的程式"""

import requests

def lookup(word):
  url = f"https://www.moedict.tw/uni/{word}"
  data = requests.get(url).json()
  return data['heteronyms'][0]['definitions'][0]['def']

lookup('教室')

gr.Interface(lookup, 'text', 'text').launch()

"""## 加入 title 及 description"""

gr.Interface(lookup, 
             'text', 
             'text',
             title="國語字典",
             description="請輸入欲查詢之國字或詞語並按下submit！").launch()

"""## 修改labels"""

gr.Interface(lookup, 
             gr.Textbox(label="輸入國字或詞語"), 
             gr.Textbox(label="查詢結果"),
             title="國語字典",
             description="請輸入欲查詢之國字或詞語並按下submit！").launch()

"""## Multple Inputs / Multple Outputs"""

def bmi(w, h):
  b = w / h**2
  if b < 18.5:
    health="體重過輕"
  elif b > 24:
    health="體重過重"
  else:
    health="健康"
  return b, health

gr.Interface(bmi, ["number", "number"], ["text","text"]).launch()

"""## 加入 Examples"""

gr.Interface(bmi, 
             ["number", "number"], 
             ["text","text"],
             examples=[
                 [80, 1.83],
                 [85, 1.83]
             ]).launch()

"""## 加入其他輸入/輸出組件"""

from PIL import Image

def process(image):
  r, g, b = image.split()
  image = Image.merge("RGB", (b, g, r))
  return image

gr.Interface(process, gr.Image(type="pil"), gr.Image(type="pil")).launch()

"""## 儲存使用者輸入的資料"""

import random

def process(image):
  image.save(f"{random.randint(0, 99999):05}.jpg")
  r, g, b = image.split()
  image = Image.merge("RGB", (b, g, r))
  return image

gr.Interface(process, gr.Image(type="pil"), gr.Image(type="pil")).launch()

"""## 限制存取"""

gr.Interface(lookup, 
             gr.Textbox(label="輸入國字或詞語"), 
             gr.Textbox(label="查詢結果"),
             title="國語字典",
             description="請輸入欲查詢之國字或詞語並按下submit！").launch(auth=('Victor','1234'))

"""## 使用from_pipeline直接載入huggingface上面的東西來使用"""

!pip install transformers

import gradio as gr
from transformers import pipeline
pipe = pipeline("image-classification")
gr.Interface.from_pipeline(pipe).launch()

pipe = pipeline("sentiment-analysis")
gr.Interface.from_pipeline(pipe).launch()

import gradio as gr
demo = gr.Interface.load("spaces/vcdemy/dictionary")
demo.launch()